"""Agents for the autonomous coding workflow.

Three agents collaborate to produce a working, tested Python implementation:

  CodeAgent   – generates (or fixes) source code
  TestAgent   – generates test files and runs them
  ReviewAgent – does a lightweight quality review

All agents use stub/mock "models" for v1; swap ``model_name`` and
implement ``_call_model`` to connect a real LLM API.
"""

from __future__ import annotations

import os
from typing import Any

from core.agent.base_agent import BaseAgent
from core.task.task import Action, Task

# ---------------------------------------------------------------------------
# Static mock responses (deterministic; no LLM call required)
# ---------------------------------------------------------------------------

_STACK_IMPLEMENTATION = '''\
"""Stack data structure – generated by CodeAgent."""


class Stack:
    """A last-in, first-out (LIFO) stack."""

    def __init__(self) -> None:
        self._items: list = []

    def push(self, item) -> None:
        """Push *item* onto the top of the stack."""
        self._items.append(item)

    def pop(self):
        """Remove and return the top item.

        Raises:
            IndexError: if the stack is empty.
        """
        if self.is_empty():
            raise IndexError("pop from empty stack")
        return self._items.pop()

    def peek(self):
        """Return the top item without removing it.

        Raises:
            IndexError: if the stack is empty.
        """
        if self.is_empty():
            raise IndexError("peek from empty stack")
        return self._items[-1]

    def is_empty(self) -> bool:
        """Return True if the stack contains no items."""
        return len(self._items) == 0

    def size(self) -> int:
        """Return the number of items in the stack."""
        return len(self._items)

    def __repr__(self) -> str:
        return f"Stack({self._items!r})"
'''

_STACK_TESTS = '''\
"""Pytest tests for the Stack implementation."""

import sys
import os

import pytest

# Allow the test to find the generated module regardless of working directory
sys.path.insert(0, os.path.dirname(__file__))
from stack import Stack  # noqa: E402


def test_push_and_pop():
    s = Stack()
    s.push(1)
    s.push(2)
    assert s.pop() == 2
    assert s.pop() == 1


def test_peek_does_not_remove():
    s = Stack()
    s.push(42)
    assert s.peek() == 42
    assert s.size() == 1


def test_is_empty_initial():
    s = Stack()
    assert s.is_empty()


def test_is_empty_after_push():
    s = Stack()
    s.push("x")
    assert not s.is_empty()


def test_pop_empty_raises():
    s = Stack()
    with pytest.raises(IndexError):
        s.pop()


def test_peek_empty_raises():
    s = Stack()
    with pytest.raises(IndexError):
        s.peek()


def test_size():
    s = Stack()
    assert s.size() == 0
    s.push(1)
    s.push(2)
    assert s.size() == 2


def test_multiple_types():
    s = Stack()
    s.push("hello")
    s.push(3.14)
    s.push([1, 2, 3])
    assert s.size() == 3
    assert s.pop() == [1, 2, 3]
    assert s.pop() == 3.14
    assert s.pop() == "hello"
'''


# ---------------------------------------------------------------------------
# CodeAgent
# ---------------------------------------------------------------------------

class CodeAgent(BaseAgent):
    """Generates (and re-generates on failure) source-code files.

    State keys read:
        phase (str)        – current workflow phase
        iteration (int)    – number of fix iterations so far
        test_results (str) – last pytest output (used to guide fixes)

    State keys written (via returned action):
        phase              – set to "test" after code is written
    """

    def __init__(self, output_dir: str) -> None:
        super().__init__(
            name="CodeAgent",
            role="code_generator",
            model_name="mock",
            tools=["write_file"],
        )
        self.output_dir = output_dir

    def can_act(self, task: Task, state: dict[str, Any]) -> bool:
        return state.get("phase") in {None, "code", "fix"}

    def act(self, task: Task, state: dict[str, Any]) -> Action:
        phase = state.get("phase", "code")
        iteration = state.get("iteration", 0)

        code = self._generate_code(task.goal, state)
        code_path = os.path.join(self.output_dir, "stack.py")

        # After writing the code, signal the engine to move to the test phase.
        state["phase"] = "test"
        state["code_path"] = code_path
        state["iteration"] = iteration + 1

        return Action(
            type="tool_call",
            tool_name="write_file",
            tool_input={"path": code_path, "content": code},
            message=f"Writing code (iteration {iteration + 1})",
        )

    def _generate_code(self, goal: str, state: dict[str, Any]) -> str:
        """Return source code for the goal.

        In v1 this returns a hardcoded stack implementation.  In a real
        system this would call an LLM API with the goal and any failure
        feedback from previous iterations.
        """
        return _STACK_IMPLEMENTATION


# ---------------------------------------------------------------------------
# TestAgent
# ---------------------------------------------------------------------------

class TestAgent(BaseAgent):
    """Writes test files and runs them using pytest.

    State keys read:
        phase     – must be "test" to activate
        code_path – path to the generated source file
        test_path – path to the test file (set by this agent after writing)

    State keys written (via returned action or state mutation):
        phase     – set to "review" on pass, "fix" on failure
        test_path – path to the generated test file
    """

    # Prevent pytest from attempting to collect this class as a test suite.
    __test__ = False

    _WRITE  = "writing_tests"
    _RUN    = "running_tests"

    def __init__(self, output_dir: str) -> None:
        super().__init__(
            name="TestAgent",
            role="test_runner",
            model_name="mock",
            tools=["write_file", "run_tests"],
        )
        self.output_dir = output_dir

    def can_act(self, task: Task, state: dict[str, Any]) -> bool:
        return state.get("phase") == "test"

    def act(self, task: Task, state: dict[str, Any]) -> Action:
        sub_phase = state.get("test_sub_phase", self._WRITE)

        if sub_phase == self._WRITE:
            test_path = os.path.join(self.output_dir, "test_stack.py")
            state["test_path"] = test_path
            state["test_sub_phase"] = self._RUN

            return Action(
                type="tool_call",
                tool_name="write_file",
                tool_input={"path": test_path, "content": _STACK_TESTS},
                message="Writing test file",
            )

        # sub_phase == _RUN
        test_path = state["test_path"]
        last_result = state.get("last_tool_result", {})

        # Check if we just finished running tests
        if state.get("tests_ran"):
            success = last_result.get("success", False)
            if success:
                state["phase"] = "review"
            else:
                state["phase"] = "fix"
                state["test_results"] = last_result.get("output", "")
                state["test_sub_phase"] = self._WRITE  # reset for next iteration
            state["tests_ran"] = False
            # Yield control to next agent by returning a message
            return Action(
                type="message",
                message="Tests complete" if success else "Tests failed – handing off to CodeAgent for a fix",
            )

        # First time in _RUN sub-phase: trigger the test runner
        state["tests_ran"] = True
        return Action(
            type="tool_call",
            tool_name="run_tests",
            tool_input={"path": test_path},
            message="Running tests",
        )


# ---------------------------------------------------------------------------
# ReviewAgent
# ---------------------------------------------------------------------------

class ReviewAgent(BaseAgent):
    """Performs a lightweight code-quality review.

    In v1 this is a stub: it checks that the code file exists and is
    non-empty, then marks the task done.

    State keys read:
        phase     – must be "review"
        code_path – path to the source file
    """

    def __init__(self) -> None:
        super().__init__(
            name="ReviewAgent",
            role="reviewer",
            model_name="mock",
            tools=["read_file"],
        )

    def can_act(self, task: Task, state: dict[str, Any]) -> bool:
        return state.get("phase") == "review"

    def act(self, task: Task, state: dict[str, Any]) -> Action:
        code_path = state.get("code_path", "")
        review_done = state.get("review_done", False)

        if not review_done:
            # Read the code for review
            state["review_done"] = True
            return Action(
                type="tool_call",
                tool_name="read_file",
                tool_input={"path": code_path},
                message="Reading code for review",
            )

        # Review complete – signal done
        last_result = state.get("last_tool_result", {})
        code_content = last_result.get("output", "")
        notes = self._review(code_content)
        return Action(
            type="done",
            message=f"Code review passed. Notes: {notes}",
        )

    def _review(self, code: str) -> str:
        """Very lightweight heuristic review (stub for v1)."""
        checks: list[str] = []
        if "class " in code:
            checks.append("defines a class")
        if "def " in code:
            checks.append("has methods")
        if '"""' in code or "'''" in code:
            checks.append("has docstrings")
        if checks:
            return "OK – " + ", ".join(checks)
        return "OK"
