"""Agents for the autonomous coding workflow."""

from __future__ import annotations

import os
from typing import Any

from core.agent.base_agent import BaseAgent
from core.task.task import Action, Task

_STACK_IMPLEMENTATION = '''\
"""Stack data structure - generated by CodeAgent."""


class Stack:
    """A last-in, first-out (LIFO) stack."""

    def __init__(self) -> None:
        self._items: list = []

    def push(self, item) -> None:
        """Push *item* onto the top of the stack."""
        self._items.append(item)

    def pop(self):
        """Remove and return the top item.

        Raises:
            IndexError: if the stack is empty.
        """
        if self.is_empty():
            raise IndexError("pop from empty stack")
        return self._items.pop()

    def peek(self):
        """Return the top item without removing it.

        Raises:
            IndexError: if the stack is empty.
        """
        if self.is_empty():
            raise IndexError("peek from empty stack")
        return self._items[-1]

    def is_empty(self) -> bool:
        """Return True if the stack contains no items."""
        return len(self._items) == 0

    def size(self) -> int:
        """Return the number of items in the stack."""
        return len(self._items)

    def __repr__(self) -> str:
        return f"Stack({self._items!r})"
'''

_STACK_TESTS = '''\
"""Pytest tests for the Stack implementation."""

import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(__file__))
from stack import Stack  # noqa: E402


def test_push_and_pop():
    s = Stack()
    s.push(1)
    s.push(2)
    assert s.pop() == 2
    assert s.pop() == 1


def test_peek_does_not_remove():
    s = Stack()
    s.push(42)
    assert s.peek() == 42
    assert s.size() == 1


def test_is_empty_initial():
    s = Stack()
    assert s.is_empty()


def test_is_empty_after_push():
    s = Stack()
    s.push("x")
    assert not s.is_empty()


def test_pop_empty_raises():
    s = Stack()
    with pytest.raises(IndexError):
        s.pop()


def test_peek_empty_raises():
    s = Stack()
    with pytest.raises(IndexError):
        s.peek()


def test_size():
    s = Stack()
    assert s.size() == 0
    s.push(1)
    s.push(2)
    assert s.size() == 2
'''


class CodeAgent(BaseAgent):
    """Generates source-code files."""

    def __init__(self, output_dir: str) -> None:
        super().__init__(
            name="CodeAgent",
            role="code_generator",
            model_name="mock",
            tools=["write_file"],
        )
        self.output_dir = output_dir

    def can_act(self, task: Task, state: dict[str, Any]) -> bool:
        return state.get("phase") in {None, "code", "fix"}

    def act(self, task: Task, state: dict[str, Any]) -> Action:
        del task
        iteration = state.get("iteration", 0)
        code_path = os.path.join(self.output_dir, "stack.py")
        return Action(
            type="tool_call",
            tool_name="write_file",
            tool_input={"path": code_path, "content": _STACK_IMPLEMENTATION},
            message=f"Writing code (iteration {iteration + 1})",
            metadata={
                "next_phase": "test",
                "state_updates": {
                    "code_path": code_path,
                    "iteration": iteration + 1,
                },
                "output_updates": {"generated_code_path": code_path},
            },
        )


class TestAgent(BaseAgent):
    """Writes tests and runs them using pytest."""

    __test__ = False
    _WRITE = "writing_tests"
    _RUN = "running_tests"

    def __init__(self, output_dir: str) -> None:
        super().__init__(
            name="TestAgent",
            role="test_runner",
            model_name="mock",
            tools=["write_file", "run_tests"],
        )
        self.output_dir = output_dir

    def can_act(self, task: Task, state: dict[str, Any]) -> bool:
        del task
        return state.get("phase") == "test"

    def act(self, task: Task, state: dict[str, Any]) -> Action:
        del task
        sub_phase = state.get("test_sub_phase", self._WRITE)
        if sub_phase == self._WRITE:
            test_path = os.path.join(self.output_dir, "test_stack.py")
            return Action(
                type="tool_call",
                tool_name="write_file",
                tool_input={"path": test_path, "content": _STACK_TESTS},
                message="Writing test file",
                metadata={
                    "state_updates": {
                        "test_path": test_path,
                        "test_sub_phase": self._RUN,
                    },
                    "output_updates": {"generated_test_path": test_path},
                },
            )

        test_path = state["test_path"]
        last_result = state.get("last_tool_result", {})
        if state.get("tests_ran"):
            success = last_result.get("success", False)
            return Action(
                type="message",
                message="Tests complete"
                if success
                else "Tests failed - handing off to CodeAgent for a fix",
                metadata={
                    "next_phase": "review" if success else "fix",
                    "state_updates": {
                        "tests_ran": False,
                        "test_sub_phase": self._RUN if success else self._WRITE,
                        "test_results": last_result.get("output", "")
                        if not success
                        else "",
                    },
                    "output_updates": {
                        "tests_passed": success,
                        "test_run_output": last_result.get("output", ""),
                    },
                },
            )

        return Action(
            type="tool_call",
            tool_name="run_tests",
            tool_input={"path": test_path, "cwd": self.output_dir},
            message="Running tests",
            metadata={"state_updates": {"tests_ran": True}},
        )


class ReviewAgent(BaseAgent):
    """Performs a lightweight code-quality review."""

    def __init__(self) -> None:
        super().__init__(
            name="ReviewAgent",
            role="reviewer",
            model_name="mock",
            tools=["read_file"],
        )

    def can_act(self, task: Task, state: dict[str, Any]) -> bool:
        del task
        return state.get("phase") == "review"

    def act(self, task: Task, state: dict[str, Any]) -> Action:
        del task
        code_path = state.get("code_path", "")
        review_done = state.get("review_done", False)
        if not review_done:
            return Action(
                type="tool_call",
                tool_name="read_file",
                tool_input={"path": code_path},
                message="Reading code for review",
                metadata={"state_updates": {"review_done": True}},
            )

        code_content = state.get("last_tool_result", {}).get("output", "")
        notes = self._review(code_content)
        return Action(
            type="done",
            message=f"Code review passed. Notes: {notes}",
            metadata={"output_updates": {"review_notes": notes}},
        )

    def _review(self, code: str) -> str:
        checks: list[str] = []
        if "class " in code:
            checks.append("defines a class")
        if "def " in code:
            checks.append("has methods")
        if '"""' in code or "'''" in code:
            checks.append("has docstrings")
        return "OK - " + ", ".join(checks) if checks else "OK"
